### ISSUE TITLE
Create statistics functionality

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord-bot#98]

**Comment by ajar** [comment]
Could we please flesh this out or link off to a thread in Discord? @LunaUrsa

**Comment by LunaUrsa** [comment]
We want to replicate the statistics functionality that mee6 has. For example:

Online members

Peak online members

Number of VIP roles(level 5)

Number of DJ roles(level 10)

Number of Patreon +Booster roles

Subreddit subscribers (wishlist)

Twitter followers (wishlist)

Facebook followers (wishlist)

**Comment by LunarUrsan** [comment]
![image](https://user-images.githubusercontent.com/96215382/204296055-5457197e-c34f-48fb-85f0-33532a12519e.png)
